/* tslint:disable:object-literal-key-quotes */
const data = {
  topics: [
    { id: '0', name: 'Human Firewall', slot: 1 },
    { id: '1', name: 'Protection', slot: 1 },
    { id: '2', name: 'Detection & Response', slot: 1 },
    { id: '3', name: 'Sec. Architecture & Innovation', slot: 2 },
    { id: '4', name: 'Gov., Risk, Compliance', slot: 2 },
  ],
  sessionHolders: {
    '0': ['Holder1', 'Holder2'],
    '1': ['Holder3', 'Holder4', 'Holder5'],
    '2': ['Holder6', 'Holder7', 'Holder8'],
    '3': ['Holder10', 'Holder11', 'Holder12'],
    '4': ['Holder13', 'Holder14'],
  },
  votes: [
    { topicId: '0', person: 'A', prio: 1 },
    { topicId: '4', person: 'A', prio: 2 },
    { topicId: '3', person: 'A', prio: 3 },
    { topicId: '3', person: 'B', prio: 1 },
    { topicId: '4', person: 'B', prio: 2 },
    { topicId: '1', person: 'B', prio: 3 },
    { topicId: '3', person: 'C', prio: 1 },
    { topicId: '1', person: 'C', prio: 2 },
    { topicId: '2', person: 'C', prio: 3 },
    { topicId: '4', person: 'D', prio: 1 },
    { topicId: '0', person: 'D', prio: 2 },
    { topicId: '3', person: 'D', prio: 3 },
    { topicId: '2', person: 'E', prio: 1 },
    { topicId: '1', person: 'E', prio: 2 },
    { topicId: '4', person: 'E', prio: 3 },
    { topicId: '0', person: 'F', prio: 1 },
    { topicId: '3', person: 'F', prio: 2 },
    { topicId: '1', person: 'F', prio: 3 },
    { topicId: '1', person: 'G', prio: 1 },
    { topicId: '3', person: 'G', prio: 2 },
    { topicId: '4', person: 'G', prio: 3 },
    { topicId: '4', person: 'H', prio: 1 },
    { topicId: '3', person: 'H', prio: 2 },
    { topicId: '2', person: 'H', prio: 3 },
    { topicId: '3', person: 'I', prio: 1 },
    { topicId: '4', person: 'I', prio: 2 },
    { topicId: '1', person: 'I', prio: 3 },
    { topicId: '4', person: 'J', prio: 1 },
    { topicId: '2', person: 'J', prio: 2 },
    { topicId: '1', person: 'J', prio: 3 },
    { topicId: '1', person: 'K', prio: 1 },
    { topicId: '2', person: 'K', prio: 2 },
    { topicId: '3', person: 'K', prio: 3 },
    { topicId: '2', person: 'L', prio: 1 },
    { topicId: '0', person: 'L', prio: 2 },
    { topicId: '1', person: 'L', prio: 3 },
    { topicId: '1', person: 'M', prio: 1 },
    { topicId: '2', person: 'M', prio: 2 },
    { topicId: '4', person: 'M', prio: 3 },
    { topicId: '0', person: 'N', prio: 1 },
    { topicId: '2', person: 'N', prio: 2 },
    { topicId: '1', person: 'N', prio: 3 },
    { topicId: '0', person: 'O', prio: 1 },
    { topicId: '4', person: 'O', prio: 2 },
    { topicId: '1', person: 'O', prio: 3 },
    { topicId: '1', person: 'P', prio: 1 },
    { topicId: '3', person: 'P', prio: 2 },
    { topicId: '4', person: 'P', prio: 3 },
    { topicId: '4', person: 'Q', prio: 1 },
    { topicId: '3', person: 'Q', prio: 2 },
    { topicId: '0', person: 'Q', prio: 3 },
  ],
  config: { participants: 30, criticers: 3, discussers: 6, slots: 2 },
};
export { data };
