name: CI
on: [push]
jobs:
  build:
    name: On node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12.x', '13.x']
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./dot-staffer-app
        run: npm ci
      - name: Install dependencies logic
        working-directory: ./logic
        run: npm ci
      - name: Compile lib
        working-directory: ./logic
        run: npm build
      - name: Lint
        working-directory: ./dot-staffer-app
        run: npm run lint
      - name: Build
        working-directory: ./dot-staffer-app
        run: npm run build -- --prod --base-href=/dot-staffer/
      # - name: Test
      #   run: npm test -- --configuration=ci
      # - name: E2E
      #   run: npm run e2e -- --configuration=ci
      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: dot-staffer-app/dist/dot-staffer-app
          GH_PAT: ${{ secrets.GH_PAT }}
          CI: true
